[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "tVP3GDjVPoUKhqLmMadcrv2Zr4ssUR53EiTA7MZJThv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/raj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
